### ISSUE TITLE
To maintain data integrity, provide appropriate data types for each column and create appropriate connections between the tables, such as foreign key constraints.

### ISSUE THREAD

**Issue by gopiraju3** [WSUCEG-7140/cinebook-teamL#27]
Definition of done:

As a developer, I have to maintain data integrity, provide appropriate data types for each column and create appropriate connections between the tables, such as foreign key constraints.

**Comment by Swathi72001** [comment]
handeled By spring mongoDb Connectiond

**Comment by Harishkumar110411** [comment]
This is an important improvement as it ensures data integrity through the use of appropriate data types and foreign key constraints, leading to a more reliable and consistent database. Well done on implementing these crucial measures!

**Comment by Nallapati25** [comment]
This feature improves the data in the tables looks in a better way. This also makes the user to enter the proper data.

**Comment by harikaboppudi10** [comment]
Maintaining data integrity is crucial for any database system. By providing appropriate data types for each column and establishing appropriate connections between tables using foreign key constraints, we can ensure data consistency and reliability.
