### ISSUE TITLE
Make an API to implement a reporting function that produces a report on ticket sales

### ISSUE THREAD

**Issue by gopiraju3** [WSUCEG-7140/cinebook-teamL#28]
Definition of Done:

- Develop the logic to generate the ticket sales report based on the collected data.
- Define the structure and format of the report, such as JSON, CSV, or PDF, based on the requirements and intended use of the information.
- Unit tests are written to ensure the functionality of this API endpoint.

**Comment by harikaboppudi10** [comment]
By implementing this reporting API, developers can empower  valuable insights into ticket sales, enabling to make informed decisions and improve overall business performance.

**Comment by Harishkumar110411** [comment]
Valuable enhancement! The new API for reporting ticket sales provides insightful data on total tickets sold, revenue, and top-selling movies, enabling informed decision-making for improved sales strategies. Well done on implementing this important feature!
