### ISSUE TITLE
No credentials are required to sign in as a visitor.

### ISSUE THREAD

**Issue by gopiraju3** [WSUCEG-7140/cinebook-teamL#29]
Definition of Done:

As a developer, 

- I have to Implement a mechanism that allows users to access the system as a visitor without requiring any registration or credentials.

**Comment by harikaboppudi10** [comment]
Allowing visitors to sign in without requiring credentials simplifies  and encourages users to explore the platform without any barriers. This means more users can quickly access the platform's content, boosting user engagement and potentially attracting new customers.
