### ISSUE TITLE
The viewer can view the summary of the film by clicking on it, which includes the plot, rating, and showtime.

### ISSUE THREAD

**Issue by gopiraju3** [WSUCEG-7140/cinebook-teamL#35]
Definition of done:

As a Developer, I have to retrieve the necessary film information from the appropriate data source, such as a database or API. This data should include the film's plot, rating, and showtime information.

**Comment by Harishkumar110411** [comment]
implementing the feature where  viewers can click on a flim to access the summery including plot,rating and showtime will greatly enhance the user experience and provide the valuable information at a glance

**Comment by harikaboppudi10** [comment]
By implementing this, the platform can provide a delightful and informative experience to its users, encouraging them to explore and engage with the films available on the platform.
